spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:khelp_read}
      auto-index-creation: true

app:
  mongodb:
    connection-pool:
      max-size: 10
      min-size: 2
