spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      authentication-database: admin
      auto-index-creation: false  # 프로덕션에서는 수동으로 인덱스 관리

app:
  mongodb:
    connection-pool:
      max-size: 50
      min-size: 10
      max-wait-time: 5000
      max-connection-idle-time: 60000
      max-connection-life-time: 120000
